#!/bin/bash
set -euo pipefail
mkdir -p $HOME/Desktop

# Copy desktop files over on container start rather than on postBuild
# In JupyterHubs, $HOME in build time is not available during runtime
# as $HOME is usually a persistent directory mounted per user
cp $REPO_DIR/Firefox.desktop $HOME/Desktop/
mkdir -p $HOME/.vnc/
cp $REPO_DIR/config $HOME/.vnc/
mkdir -p $HOME/.config/autostart/
cp $REPO_DIR/wallpaper.desktop $HOME/.config/autostart/

# Grant executable permissions to wallpaper script
chmod +x /home/jovyan/setWallpaper.sh

# Execute
exec "$@"
